### ISSUE TITLE
頂点カラー名にマルチバイト文字が含まれている時にメニューがバグる

### ISSUE THREAD

**Issue by nepia11** [nepia11/blender_vertex_color_master#1]
Traceback (most recent call last):
  File "/home/nepia/.config/blender/2.90/scripts/addons/vertex_color_master/vcm_menus.py", line 52, in draw
    self.draw_standard_layout(context, obj, settings)
  File "/home/nepia/.config/blender/2.90/scripts/addons/vertex_color_master/vcm_menus.py", line 62, in draw_standard_layout
    draw_src_dst_operations(context, layout, obj, settings)
  File "/home/nepia/.config/blender/2.90/scripts/addons/vertex_color_master/vcm_menus.py", line 232, in draw_src_dst_operations
    layer_info = get_layer_info(context)
  File "/home/nepia/.config/blender/2.90/scripts/addons/vertex_color_master/vcm_helpers.py", line 546, in get_layer_info
    s = settings.src_vcol_id
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by nepia11** [comment]
ちょっと違うかも　utf-8以外の文字列が含まれてるときって感じ
